### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by luozui** [endiliey/idne#1]
Dear idne Maintainers,

As I was following the tutorial, at the following jupyter notebook line

`idne 454A A.cpp`

I get the following error

```
Traceback (most recent call last):
  File "/usr/local/bin/idne", line 9, in <module>
    load_entry_point('Idne', 'console_scripts', 'idne')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/neo/idne/idne.py", line 42, in cli
    enter_form['handle'] = config.username
  File "/usr/local/lib/python2.7/dist-packages/robobrowser/forms/form.py", line 216, in __setitem__
    self.fields[key].value = value
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/datastructures.py", line 784, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

**Comment by endiliey** [comment]
Hi. Thanks for opening up the issue. I'm currently away but I'll look into this asap. It might be related to jupyter notebook incompatibility as I've never tested it using jupyter. 

Appreciate it if you have a GitHub repository where I can clone & test.

**Comment by endiliey** [comment]
Fixed. Try again
